name: Build Custom Spider JAR  
  
on:  
  workflow_dispatch:  
    inputs:  
      genjar_param:  
        description: 'Parameter for genJar.bat (optional)'  
        required: false  
        default: ''  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
        
      - name: Set up JDK 11  
        uses: actions/setup-java@v4  
        with:  
          distribution: 'temurin'  
          java-version: '11'  
          cache: 'gradle'  
        
      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew  
        shell: bash  
        
      - name: Build APK with Gradle  
        run: ./gradlew assembleRelease --no-daemon  
        shell: bash  
        
      - name: Run genJar.bat  
        run: |  
          cd jar  
          ./genJar.bat ${{ github.event.inputs.genjar_param }}  
        shell: cmd  
        
      - name: Upload custom_spider.jar  
        uses: actions/upload-artifact@v4  
        with:  
          name: custom_spider  
          path: |  
            jar/custom_spider.jar  
            jar/custom_spider.jar.md5  
          retention-days: 30  
        
      - name: Display MD5  
        run: type jar\custom_spider.jar.md5  
        shell: cmd
